apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: '{{NAMESPACE}}-default-mtls'
  namespace: '{{NAMESPACE}}'
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: '{{NAMESPACE}}-deny-all'
  namespace: '{{NAMESPACE}}'
spec:
  action: DENY
  rules:
  - from:
    - source:
        notPrincipals: ["cluster.local/ns/{{NAMESPACE}}/sa/*"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: '{{NAMESPACE}}-allow-ingress'
  namespace: '{{NAMESPACE}}'
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/aks-istio-ingress/sa/aks-istio-ingressgateway-external"]
  - from:
    - source:
        principals: ["cluster.local/ns/aks-istio-system/sa/istiod"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: '{{SERVICE_NAME}}-service-policy'
  namespace: '{{NAMESPACE}}'
spec:
  selector:
    matchLabels:
      app: '{{SERVICE_NAME}}'
  action: ALLOW
  rules:
  - from:
    - source:
        principals: {{ALLOWED_PRINCIPALS | default('["cluster.local/ns/' + NAMESPACE + '/sa/default"]')}}
    to:
    - operation:
        methods: {{ALLOWED_METHODS | default('["GET", "POST"]')}}
        paths: {{ALLOWED_PATHS | default('["/health", "/metrics"]')}}
  - when:
    - key: source.ip
      notValues: {{BLOCKED_IPS | default('["0.0.0.0/0"]')}}
