# Valores para ambiente de STAGING
# Herda configurações base do values.yaml

# Configurações específicas do staging
app:
  name: pets
  version: "1.0.0"
  namespace: pets-staging

# Metadados específicos
metadata:
  labels:
    managed_by: istio-blueprints
    business_unit: petshop
    environment: staging
  annotations:
    owner: platform-team@contoso.com
    deployment-strategy: blue-green

# Configurações de rede para staging
network:
  gateway:
    name: pets-gateway-staging
    namespace: aks-istio-ingress
    hosts:
      - pets-staging.contoso.com
    tls:
      enabled: true
      secretName: pets-staging-tls
  
  virtualservice:
    name: pets-staging
    gateways:
      - pets-gateway-staging
    routing:
      primary:
        weight: 90
        subset: primary
      canary:
        weight: 10
        subset: canary

# Configurações de segurança (mais permissivo em staging)
security:
  mtls:
    mode: PERMISSIVE
  peerAuthentication:
    name: default-staging

# Service discovery
service:
  host: pets.pets-staging.svc.cluster.local
  port: 80
  subsets:
    primary:
      version: v1
    canary:
      version: v2
