# =============================================================================
# Schema de Validação para values.yaml - Templates Istio AKS
# =============================================================================
# Este arquivo define a estrutura e validações para o values.yaml
# Compatível com JSON Schema Draft 7

$schema: "http://json-schema.org/draft-07/schema#"
$id: "https://example.com/istio-templates-schema.json"
title: "Istio Templates Configuration Schema"
description: "Schema para validação da configuração dos templates Istio"
type: "object"

# Propriedades requeridas na raiz
required:
  - "global"
  - "trafficManagement"
  - "security"
  - "observability"
  - "resilience"
  - "policiesGovernance"
  - "extensibility"
  - "additionalFeatures"
  - "environments"

properties:
  # =============================================================================
  # CONFIGURAÇÕES GLOBAIS
  # =============================================================================
  global:
    type: "object"
    required:
      - "namespace"
      - "environment"
      - "cluster"
    properties:
      namespace:
        type: "string"
        pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
        maxLength: 63
        description: "Namespace Kubernetes válido"
      labels:
        type: "object"
        patternProperties:
          "^[a-zA-Z0-9]([-a-zA-Z0-9_.]*[a-zA-Z0-9])?$":
            type: "string"
      environment:
        type: "string"
        enum: ["dev", "staging", "prod"]
        description: "Ambiente de execução"
      cluster:
        type: "object"
        required:
          - "name"
          - "region"
        properties:
          name:
            type: "string"
            minLength: 1
          region:
            type: "string"
            minLength: 1

  # =============================================================================
  # GERENCIAMENTO DE TRÁFEGO
  # =============================================================================
  trafficManagement:
    type: "object"
    required: ["enabled"]
    properties:
      enabled:
        type: "boolean"
      gateway:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          name:
            type: "string"
            pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
          hosts:
            type: "array"
            items:
              type: "string"
              format: "hostname"
          environments:
            type: "object"
            properties:
              dev:
                $ref: "#/definitions/environmentHosts"
              staging:
                $ref: "#/definitions/environmentHosts"
              prod:
                $ref: "#/definitions/environmentHosts"
      virtualService:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          canaryRouting:
            type: "object"
            properties:
              enabled:
                type: "boolean"
              stableWeight:
                type: "integer"
                minimum: 0
                maximum: 100
              canaryWeight:
                type: "integer"
                minimum: 0
                maximum: 100
          timeout:
            type: "string"
            pattern: "^[0-9]+(s|m|h)$"
          retries:
            type: "object"
            properties:
              attempts:
                type: "integer"
                minimum: 1
                maximum: 10
              perTryTimeout:
                type: "string"
                pattern: "^[0-9]+(s|m|h)$"
      destinationRule:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          loadBalancer:
            type: "object"
            properties:
              simple:
                type: "string"
                enum: ["ROUND_ROBIN", "LEAST_CONN", "RANDOM", "PASSTHROUGH"]
          circuitBreaker:
            type: "object"
            properties:
              enabled:
                type: "boolean"
              consecutiveErrors:
                type: "integer"
                minimum: 1
              interval:
                type: "string"
                pattern: "^[0-9]+(s|m|h)$"
              baseEjectionTime:
                type: "string"
                pattern: "^[0-9]+(s|m|h)$"

  # =============================================================================
  # SEGURANÇA
  # =============================================================================
  security:
    type: "object"
    required: ["enabled"]
    properties:
      enabled:
        type: "boolean"
      peerAuthentication:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          mtlsMode:
            type: "string"
            enum: ["STRICT", "PERMISSIVE", "DISABLE"]
          scope:
            type: "string"
            enum: ["namespace", "workload"]
      authorizationPolicy:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          defaultAction:
            type: "string"
            enum: ["ALLOW", "DENY"]
          rules:
            type: "array"
            items:
              type: "object"
              required: ["name", "action"]
              properties:
                name:
                  type: "string"
                  pattern: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
                action:
                  type: "string"
                  enum: ["ALLOW", "DENY"]
                source:
                  type: "object"
                operation:
                  type: "object"
      requestAuthentication:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          jwt:
            type: "object"
            properties:
              issuer:
                type: "string"
                format: "uri"
              audiences:
                type: "array"
                items:
                  type: "string"
              jwksUri:
                type: "string"
                format: "uri"

  # =============================================================================
  # OBSERVABILIDADE
  # =============================================================================
  observability:
    type: "object"
    required: ["enabled"]
    properties:
      enabled:
        type: "boolean"
      telemetry:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          metrics:
            type: "object"
            properties:
              enabled:
                type: "boolean"
              custom:
                type: "array"
                items:
                  type: "object"
                  required: ["name"]
                  properties:
                    name:
                      type: "string"
                    dimensions:
                      type: "object"
          tracing:
            type: "object"
            properties:
              enabled:
                type: "boolean"
              sampling:
                type: "number"
                minimum: 0
                maximum: 1
              provider:
                type: "string"
                enum: ["jaeger", "zipkin", "datadog", "lightstep"]
          accessLogs:
            type: "object"
            properties:
              enabled:
                type: "boolean"
              format:
                type: "string"
      serviceMonitor:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          interval:
            type: "string"
            pattern: "^[0-9]+(s|m|h)$"
          scrapeTimeout:
            type: "string"
            pattern: "^[0-9]+(s|m|h)$"

  # =============================================================================
  # RESILIÊNCIA
  # =============================================================================
  resilience:
    type: "object"
    required: ["enabled"]
    properties:
      enabled:
        type: "boolean"
      faultInjection:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          delay:
            type: "object"
            properties:
              enabled:
                type: "boolean"
              percentage:
                type: "number"
                minimum: 0
                maximum: 100
              fixedDelay:
                type: "string"
                pattern: "^[0-9]+(s|m|h)$"
          abort:
            type: "object"
            properties:
              enabled:
                type: "boolean"
              percentage:
                type: "number"
                minimum: 0
                maximum: 100
              httpStatus:
                type: "integer"
                minimum: 100
                maximum: 599
      retryPolicy:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          attempts:
            type: "integer"
            minimum: 1
            maximum: 10
          perTryTimeout:
            type: "string"
            pattern: "^[0-9]+(s|m|h)$"
          retryOn:
            type: "string"
      timeout:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          request:
            type: "string"
            pattern: "^[0-9]+(s|m|h)$"
          idle:
            type: "string"
            pattern: "^[0-9]+(s|m|h)$"

  # =============================================================================
  # POLÍTICAS E GOVERNANÇA
  # =============================================================================
  policiesGovernance:
    type: "object"
    required: ["enabled"]
    properties:
      enabled:
        type: "boolean"
      networkPolicy:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          defaultIngress:
            type: "string"
            enum: ["ALLOW", "DENY"]
          defaultEgress:
            type: "string"
            enum: ["ALLOW", "DENY"]
          customRules:
            type: "array"
            items:
              type: "object"
              required: ["name", "from", "to"]
              properties:
                name:
                  type: "string"
                from:
                  type: "string"
                to:
                  type: "string"
                ports:
                  type: "array"
                  items:
                    type: "integer"
                    minimum: 1
                    maximum: 65535
      securityPolicy:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          vulnerabilityScanning:
            type: "boolean"
          imagePolicy:
            type: "object"
            properties:
              allowedRegistries:
                type: "array"
                items:
                  type: "string"
              requiredAnnotations:
                type: "array"
                items:
                  type: "string"

  # =============================================================================
  # EXTENSIBILIDADE
  # =============================================================================
  extensibility:
    type: "object"
    required: ["enabled"]
    properties:
      enabled:
        type: "boolean"
      wasmFilters:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          filters:
            type: "array"
            items:
              type: "object"
              required: ["name", "image"]
              properties:
                name:
                  type: "string"
                image:
                  type: "string"
                configuration:
                  type: "object"
      envoyFilter:
        type: "object"
        properties:
          enabled:
            type: "boolean"

  # =============================================================================
  # FEATURES ADICIONAIS
  # =============================================================================
  additionalFeatures:
    type: "object"
    required: ["enabled"]
    properties:
      enabled:
        type: "boolean"
      multiCluster:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          clusters:
            type: "array"
            items:
              type: "object"
              required: ["name", "endpoint"]
              properties:
                name:
                  type: "string"
                endpoint:
                  type: "string"
                  format: "hostname"
      externalServices:
        type: "object"
        properties:
          enabled:
            type: "boolean"
          services:
            type: "array"
            items:
              type: "object"
              required: ["name", "hosts", "ports"]
              properties:
                name:
                  type: "string"
                hosts:
                  type: "array"
                  items:
                    type: "string"
                    format: "hostname"
                ports:
                  type: "array"
                  items:
                    type: "object"
                    required: ["number", "name", "protocol"]
                    properties:
                      number:
                        type: "integer"
                        minimum: 1
                        maximum: 65535
                      name:
                        type: "string"
                      protocol:
                        type: "string"
                        enum: ["HTTP", "HTTPS", "TCP", "UDP"]

  # =============================================================================
  # CONFIGURAÇÕES POR AMBIENTE
  # =============================================================================
  environments:
    type: "object"
    required: ["dev", "staging", "prod"]
    properties:
      dev:
        $ref: "#/definitions/environmentConfig"
      staging:
        $ref: "#/definitions/environmentConfig"
      prod:
        $ref: "#/definitions/environmentConfig"

# =============================================================================
# DEFINIÇÕES REUTILIZÁVEIS
# =============================================================================
definitions:
  environmentHosts:
    type: "object"
    properties:
      hosts:
        type: "array"
        items:
          type: "string"
          format: "hostname"

  environmentConfig:
    type: "object"
    properties:
      security:
        type: "object"
        properties:
          peerAuthentication:
            type: "object"
            properties:
              mtlsMode:
                type: "string"
                enum: ["STRICT", "PERMISSIVE", "DISABLE"]
          authorizationPolicy:
            type: "object"
            properties:
              defaultAction:
                type: "string"
                enum: ["ALLOW", "DENY"]
      observability:
        type: "object"
        properties:
          telemetry:
            type: "object"
            properties:
              tracing:
                type: "object"
                properties:
                  sampling:
                    type: "number"
                    minimum: 0
                    maximum: 1
      resilience:
        type: "object"
        properties:
          faultInjection:
            type: "object"
            properties:
              enabled:
                type: "boolean"

# Propriedades adicionais não são permitidas por padrão
additionalProperties: false