apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: '{{SERVICE_NAME}}-gateway'
  namespace: '{{NAMESPACE}}'
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '{{HOST}}'
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: '{{TLS_SECRET_NAME}}' # This should match the secret created for the certificate
    hosts:
    - '{{HOST}}'

