# ===============================================================================
# ISTIO VIRTUAL SERVICE - Product Service
# ===============================================================================
# Advanced traffic management with retries, timeouts, and circuit breaking
# ===============================================================================
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: product-service
  namespace: production
spec:
  hosts:
  - product-service
  - product-service.production.svc.cluster.local
  http:
  - match:
    - headers:
        x-canary:
          exact: "true"
    route:
    - destination:
        host: product-service
        subset: canary
      weight: 100
    timeout: 5s
    retries:
      attempts: 3
      perTryTimeout: 1.5s
      retryOn: gateway-error,connect-failure,refused-stream,5xx
  
  - route:
    - destination:
        host: product-service
        subset: stable
      weight: 100
    timeout: 5s
    retries:
      attempts: 3
      perTryTimeout: 1.5s
      retryOn: gateway-error,connect-failure,refused-stream
    
    # Fault injection for chaos testing (disabled by default)
    # fault:
    #   delay:
    #     percentage:
    #       value: 1
    #     fixedDelay: 2s
---
# ===============================================================================
# ISTIO DESTINATION RULE - Product Service
# ===============================================================================
# Connection pooling, load balancing, and outlier detection
# ===============================================================================
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: product-service
  namespace: production
spec:
  host: product-service
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
      localityLbSetting:
        enabled: true
    connectionPool:
      tcp:
        maxConnections: 1000
        connectTimeout: 3s
        tcpKeepalive:
          time: 7200s
          interval: 75s
      http:
        http1MaxPendingRequests: 1024
        http2MaxRequests: 1024
        maxRequestsPerConnection: 100
        idleTimeout: 3600s
        h2UpgradePolicy: UPGRADE
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
      minHealthPercent: 50
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
---
# ===============================================================================
# SIDECAR - Default Egress Configuration
# ===============================================================================
# Restrict outbound traffic to registered services only
# ===============================================================================
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
  namespace: production
spec:
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
  egress:
  - hosts:
    - "./*"
    - "istio-system/*"
---
# ===============================================================================
# SERVICE ENTRY - External API Access
# ===============================================================================
# Whitelist external services
# ===============================================================================
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-payment-api
  namespace: production
spec:
  hosts:
  - api.stripe.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: azure-services
  namespace: production
spec:
  hosts:
  - "*.vault.azure.net"
  - "*.cosmos.azure.com"
  - "*.blob.core.windows.net"
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS
