---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    version: {{ .Values.app.version }}
    environment: {{ .Values.metadata.labels.environment }}
    managed-by: {{ .Values.metadata.labels.managed_by }}
    business_unit: {{ .Values.metadata.labels.business_unit }}
  annotations:
    owner: {{ .Values.metadata.annotations.owner }}
    "istio-templates.io/category": "traffic-management"
    "istio-templates.io/component": "destinationrule"
spec:
  host: {{ .Values.service.host }}
  subsets:
  - name: primary
    labels:
      version: {{ .Values.service.subsets.primary.version }}
  - name: canary
    labels:
      version: {{ .Values.service.subsets.canary.version }}