# Istio Templates - Valores Padrão
# Configuração base para todos os ambientes

# Configurações da aplicação
app:
  name: pets
  version: 1.0.0
  namespace: pets

# Metadados padrão
metadata:
  labels:
    managed_by: istio-blueprints
    business_unit: petshop
    environment: demo
  annotations:
    owner: platform-team@contoso.com

# Configurações de rede
network:
  gateway:
    name: pets-gateway
    namespace: aks-istio-ingress
    hosts:
      - pets.contoso.com
    tls:
      enabled: true
      secretName: pets-tls
  virtualservice:
    name: pets
    gateways:
      - pets-gateway
    routing:
      primary:
        weight: 100
        subset: primary
      canary:
        weight: 0
        subset: canary

# Configurações de segurança
security:
  mtls:
    mode: STRICT
  peerAuthentication:
    name: default

# Configurações de service discovery
service:
  host: pets.pets.svc.cluster.local
  port: 80
  subsets:
    primary:
      version: v1
    canary:
      version: v2
