---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.network.virtualservice.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
    version: {{ .Values.app.version }}
    environment: {{ .Values.metadata.labels.environment }}
    managed-by: {{ .Values.metadata.labels.managed_by }}
    business_unit: {{ .Values.metadata.labels.business_unit }}
  annotations:
    owner: {{ .Values.metadata.annotations.owner }}
    "istio-templates.io/category": "traffic-management"
    "istio-templates.io/component": "virtualservice"
spec:
  hosts:
  - {{ .Values.network.gateway.hosts[0] }}
  gateways:
  - {{ .Values.network.virtualservice.gateways[0] }}
  http:
  - name: primary-routing
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Values.service.host }}
        port:
          number: {{ .Values.service.port }}
        subset: {{ .Values.network.virtualservice.routing.primary.subset }}
      weight: {{ .Values.network.virtualservice.routing.primary.weight }}