
'name: Remove Istio Configuration

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Namespace to remove the configuration from'
        required: true
        default: 'pets'
      host:
        description: 'Host for the Ingress Gateway'
        required: true
        default: 'pets.aks-labs.com'

permissions:
  id-token: write
  contents: read

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: rg-aks-labs
          cluster-name: aks-labs

      - name: Render and Delete Istio Manifests
        run: |
          chmod +x scripts/render.sh
          
          # Render manifests to ensure we have the correct resource names to delete
          ./scripts/render.sh -f templates/base/gateway.yaml -s pets-frontend -n ${{ github.event.inputs.namespace }} -h ${{ github.event.inputs.host }} --tls-secret pets-tls-secret -o manifests
          ./scripts/render.sh -f templates/base/virtual-service.yaml -s pets-frontend -n ${{ github.event.inputs.namespace }} -h ${{ github.event.inputs.host }} --service-port 80 -o manifests
          ./scripts/render.sh -f templates/security/peer-authentication.yaml -s namespace-wide -n ${{ github.event.inputs.namespace }} -o manifests
          ./scripts/render.sh -f templates/security/authorization-policy.yaml -s pets-api -n ${{ github.event.inputs.namespace }} --caller-sa pets-frontend-sa --method GET --path "/api/pets" -o manifests
          ./scripts/render.sh -f templates/traffic-management/destination-rule.yaml -s pets-api -n ${{ github.event.inputs.namespace }} -o manifests
          ./scripts/render.sh -f templates/observability/telemetry.yaml -n ${{ github.event.inputs.namespace }} -s pets-telemetry -o manifests

          # Delete all manifests
          kubectl delete -f manifests/ --ignore-not-found=true
        working-directory: ${{ github.workspace }}
'
