'''name: Setup AKS Monitoring

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Namespace to configure for metric scraping'
        required: true
        default: 'pets'

permissions:
  id-token: write
  contents: read

jobs:
  setup-monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: rg-aks-labs
          cluster-name: aks-labs

      - name: Render and Apply Prometheus Scrape Configuration
        run: |
          chmod +x scripts/render.sh
          
          # Render the prometheus config map template
          ./scripts/render.sh -f templates/observability/prometheus-scrape-config.yaml -n ${{ github.event.inputs.namespace }} -s ${{ github.event.inputs.namespace }}-scrape-config -o manifests

          # Apply the configmap to the cluster
          kubectl apply -f manifests/
        working-directory: ${{ github.workspace }}
'''
